version: 2
jobs:
  build_test:
    docker:
      - image: circleci/openjdk:8-jdk

      - image: circleci/postgres:9.5
        environment:
        - POSTGRES_USER: circleci
        - POSTGRES_DB: facilities_assessment_test


    working_directory: ~/facilities-assessment-server

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: sudo apt-get install make postgresql-client

      - run: make test_server

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_test_results:
          path: ~/junit/

      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: build/reports/tests/
          destination: testResultsHtml

      - store_artifacts:
          path: build/libs/
          destination: jars

      - run: mkdir -p ~/jars && cp build/libs/*.jar ~/jars/.

      - persist_to_workspace:
          root: ~/jars
          paths:
            - .

  deploy_to_jss:
    # using speedier docker instead of machine
    # since all we need is ssh
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: ~/jars

      - run:
          # set KNOWN_HOST_KEY in project settings
          name: Add to known hosts
          command: |
            mkdir -p ~/.ssh && echo $KNOWN_HOST_KEY >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "1a:e5:4f:89:fd:93:89:1d:bf:08:4c:df:00:56:71:57"
      - run:
          name: Deploy with SCP
          command: |
            scp ~/jars/*.jar $JSS_USER@$JSS_HOST:~/

        # scp ~/jars/*.jar $JSS_USER@$JSS_HOST:/home/app/facilities-assessment-host/app-servers && sudo systemctl restart fab

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
      - hold:
          type: approval
          requires:
            - build_test
      - deploy_to_jss:
          requires:
            - hold
