version: 2
jobs:
  build_test:
    docker:
      - image: circleci/openjdk:8-jdk

      - image: circleci/postgres:9.5
        environment:
          - POSTGRES_USER: nhsrc
          - POSTGRES_DB: facilities-assessment_test
          - POSTGRES_PASSWORD: password


    working_directory: ~/facilities-assessment-server

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: sudo apt-get install make postgresql-client

      - run: make test_server

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/reports/tests/

      - store_artifacts:
          path: build/libs/facilities-assessment-server-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
